# Writing effective survey questions

## Cognitive Response Model

Before drafting your questions, it's helpful to understand how respondents think when answering a survey.  

The following is a **4-stage cognitive model** respondents when they complete a survey.    

> **1. Comprehension**    
> **2. Retrieval of information**    
> **3. Judgment or estimation**    
> **4. Selection of a response to the question**    

### Comprehension  
Comprehension is understanding the task and question.  

The following are tips on how to improve survey comprehension of respondents [@handbook_survey_research]:  

1. Use simple, familiar words (avoid technical terms, jargon, and slang)  
2. Use simple syntax  
3. Avoid words with ambiguous meanings, i.e., aim for wording that all respondents will interpret in the same way    
4. Strive for wording that is specific and concrete (as opposed to general and abstract)  
5. Make response options exhaustive and mutually exclusive  
6. Avoid leading or loaded questions that push respondents toward an answer  
7. Ask about one thing at a time (avoid double-barreled questions) and  
8. Avoid questions with single or double negations 

How to optimize question ordering [@handbook_survey_research]:  

1. Early questions should be easy and pleasant to answer.    
2. Questions at the very beginning of a questionnaire should explicitly address the topic of the survey.    
3. Questions on the same topic should be grouped together.    
4. Questions on the same topic should proceed from general to specific.  
5. Questions on sensitive topics that might make respondents uncomfortable should be placed at the end of the questionnaire.  
6. Only ask questions that are relevant to the respondents: filter/skip questions that do not apply.    

### Retrieval of information  
Recalling information from memory, bringing information into consciousness, explicit memory

### Judgment or estimation  
Combining, supplementing, extrapolating from information that has been retrieved.  

### Selection of a response to the question