# Generating fake data {#appendixC}

Here's the code I used to create the respondent information table 
```{r message=FALSE, warning=FALSE, eval=FALSE}
library(charlatan) # library of fake data
library(glue) # library for pasting together variables

email_domains <- c("@gmail.com", "@hotmail.com", "@outlook.com", "@me.com", "@yahoo.com")

respondent_data <- ch_generate('name', 'job', 'phone_number', n = nrow(df)) %>% 
                    separate(name, "first_name", extra = "drop", remove=FALSE) %>% 
                    mutate(email = glue("{first_lower}{email_domain}", 
                                          first_lower = tolower(first_name), 
                                          email_domain = sample(email_domains, nrow(df), replace=TRUE) ), 
                           gender = sample(c("male", "female", "other", "prefer not to say"), nrow(df), replace=TRUE, prob=c(0.55, 0.35, 0.05, 0.05)), 
                           age = sample(c("Under 18", "18-34", "35-54", "55+"), nrow(df), replace=TRUE, prob = c(0.05, 0.25, 0.40, 0.30))
        )

# add ResponseId column from survey sample
respondent_data <- df %>% select(ResponseId) %>% 
  bind_cols(respondent_data)

write_csv(respondent_data, "./sample_data/respondent_data.csv") # Store data in sample_data folder

```

```{r}
skim(respondent_data)
```



